# Generated by Django 3.2 on 2023-08-26 11:16

from django.db import migrations, models
import django.db.models.deletion
import reviews.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='rating',
            field=models.PositiveSmallIntegerField(default=django.db.models.deletion.SET_NULL, null=True, validators=[reviews.validators.validate_score_or_rating], verbose_name='Рейтинг'),
        ),
    ]
