# Generated by Django 3.2 on 2023-08-24 00:00

from django.db import migrations, models
import reviews.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='rating',
            field=models.PositiveSmallIntegerField(null=True, validators=[reviews.validators.validate_score_or_rating], verbose_name='Рейтинг'),
        ),
    ]
