# Generated by Django 3.2 on 2023-08-26 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_title_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genretitle',
            options={'verbose_name': 'Категория произведения', 'verbose_name_plural': 'Категории произведений'},
        ),
    ]
