# Generated by Django 3.2 on 2023-08-29 08:50

from django.db import migrations, models
import reviews.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20230829_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.SmallIntegerField(validators=[reviews.validators.validate_score_or_rating], verbose_name='Оценка произведения пользователем'),
        ),
    ]
